# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.1.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

workflows:
    example-workflow:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            setup: "node index.js"
